### ISSUE TITLE
training set

### ISSUE THREAD

**Issue by SillyPuffo** [zhang-yi-chi/residual-rnn#1]
hi, you did a great code. but when i tried to train your model, i find the convergence is so slow and the result is not satisfied. i suppose this is due to my dataset. i use 1000 high resolution images as training data. the input will randomly crop from high-resolution images every time. i set the epoch to 2000. could you share me what kind of dataset and the number of images you used. thanks very much

**Comment by zhang-yi-chi** [comment]
The dataset used in training was basically anime images (in both low and middle resolution) collected from multiple sources by website crawler. The number of images is ~50k.

**Comment by SillyPuffo** [comment]
got it, thank you very much!
