### ISSUE TITLE
RNN with GDN at CVPR 2021

### ISSUE THREAD

**Issue by khawar-islam** [zhang-yi-chi/residual-rnn#2]
Dear @zhang-yi-chi ,
Greetings!

**New Version of RNN with GDN**
[Paper] "Islam, Khawar, L. Minh Dang, Sujin Lee, and Hyeonjoon Moon. "Image Compression With Recurrent Neural Network and Generalized Divisive Normalization." In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition, pp. 1875-1879. 2021."
[Code] https://khawar512.github.io/cvpr/

**Comment by zhang-yi-chi** [comment]
nice work
